### PR TITLE
fixed small error

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by M4cs** [comment]
Where's the error you fixed? This is sub-quality for a PR. Closing.

**Comment by 0xflotus** [comment]
If you look at the rich diff, you can see the small typo error:

Bildschirmfoto 2020-09-29 um 10 16 06

**Comment by M4cs** [comment]
I see now thank you!

**Comment by M4cs** [comment]
If you could merge the latest and remake your PR that would be great

**Pull request closed without merging**
