### PR TITLE
[added]: repo size, resource, service badges #9

### PR DESCRIPTION
**Pull request by SuvamPrasd**
In the readme file, I have included the repo size badge, custom resource badge, and custom service badge. The user has to provide their respective link to the URL so the visitors can navigate to the respective services.

issue #9

### CODE REVIEW

**Comment by M4cs** [comment]
This isn't exactly what the issue was asking for. There is a badges section on the repo where you can put resources to different badge services. I asked you to not change any badges at the top. Please add some resources or close the PR if you cannot find any.

**Comment by SuvamPrasd** [comment]
Sorry, I made a huge mistake. I will revert the changes and add useful resource reps/API links in the readme.md

**Comment by M4cs** [comment]
Thank you! No need to be sorry :) Simple misunderstanding

**Comment by SuvamPrasd** [comment]
@M4cs finally, I removed the unnecessary badges. However, I have included badges resource links and some widgets resource links.

**Comment by M4cs** [comment]
Wonderful! Thank you so much!

**Pull request merged**
